### ISSUE TITLE
Error when user signup

### ISSUE THREAD

**Issue by cengizcoskun** [mruz/base-app#37]
Error when user signup:

Fatal error: Declaration of Baseapp\Extension\Uniqueness::validate() must be compatible with Phalcon\Validation\Validator::validate(Phalcon\Validation $validation, $attribute) in ......\app\common\extension\Uniqueness.php on line 12

![error-baseapp](https://cloud.githubusercontent.com/assets/7408472/13905845/d47475a6-eed3-11e5-941d-acb9c93dea20.jpg)

**Comment by amsharma9** [comment]
I think there is still some issue. It gives this error in php errorlog:
```PHP Fatal error:  Cannot use Phalcon\Validation as Validation because the name is already in use in C:\Wamp\www\base-app\app\common\extension\Uniqueness.php on line 5```

**Comment by amsharma9** [comment]
I still got an error. I carefully copied all your changed files to my app but I still get this error.
```[25-Apr-2016 10:10:29 Asia/Calcutta] PHP Warning:  Invalid argument supplied for foreach() in C:\Wamp\www\base-app\app\Bootstrap.php on line 468```

**Comment by mruz** [comment]
Could you debg `messages` variable? Add in the line 468
```php
echo $dump->one($messages); exit();
```

**Comment by amsharma9** [comment]
This error is not occurring now. It was probably because of some other reason. I even placed your debug statement above but it never got executed. I think it was going to that statement because of some error and now its not occuring. I will try to recreate the issue, give me some time. Thanks for your patience.
